"""initial inspection schema

Revision ID: 6f24d9ec380d
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6f24d9ec380d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('result_type', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("result_type IN ('normal_abnormal', 'normal_abnormal_na')", name='valid_result_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('inspections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('location_code_snapshot', sa.String(length=80), nullable=False),
    sa.Column('location_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('area_snapshot', sa.String(length=100), nullable=False),
    sa.Column('inspector', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.String(length=32), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'submitted')", name='valid_inspection_status'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index('ix_inspections_location_submitted', ['location_id', 'submitted_at'], unique=False)
        batch_op.create_index('ix_inspections_status_submitted', ['status', 'submitted_at'], unique=False)

    op.create_table('location_items',
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inspection_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('location_id', 'item_id'),
    sa.UniqueConstraint('location_id', 'sort_order', name='uq_location_sort_order')
    )
    op.create_table('inspection_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('item_code_snapshot', sa.String(length=80), nullable=False),
    sa.Column('item_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('category_snapshot', sa.String(length=100), nullable=False),
    sa.Column('description_snapshot', sa.Text(), nullable=False),
    sa.Column('result_type_snapshot', sa.String(length=24), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.CheckConstraint("result IN ('normal', 'abnormal', 'na') OR result IS NULL", name='valid_inspection_result'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['inspection_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'item_id', name='uq_inspection_item')
    )
    with op.batch_alter_table('inspection_results', schema=None) as batch_op:
        batch_op.create_index('ix_inspection_results_inspection', ['inspection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_results', schema=None) as batch_op:
        batch_op.drop_index('ix_inspection_results_inspection')

    op.drop_table('inspection_results')
    op.drop_table('location_items')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index('ix_inspections_status_submitted')
        batch_op.drop_index('ix_inspections_location_submitted')

    op.drop_table('inspections')
    op.drop_table('locations')
    op.drop_table('inspection_items')
    # ### end Alembic commands ###
